/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editors;

import java.util.concurrent.Callable;

/**
 *
 * @author nathan
 */
public class guiComboBox<T extends Object> extends javax.swing.JComponent {

    /**
     * Creates new form guiComboBox
     */
    public guiComboBox() {
        initComponents();
    }
    
    public guiComboBox(Iterable<T> items) {
        initComponents();
        this.showNewButton(false);
    }
    
    public guiComboBox(Iterable<T> items, Callable<T> newObject) {
        this(items);
        this.showNewButton(true);
    }
    
    private void showNewButton(boolean show) {
        this.jButtonNew.setVisible(show);
        if(show) {
            
        }
        else {
            
        }
    }
    
    public void setItems(Iterable<T> items) {
        jComboBoxItems.setModel(guiHelper.getComboBoxModel(items));
    }
    
    public int getSelectedIndex() {
        return jComboBoxItems.getSelectedIndex();
    }
    
    public void setSelectedIndex(int index) {
        jComboBoxItems.setSelectedIndex(index);
    }
    
    public T getSelectedItem() {
        return (T)jComboBoxItems.getSelectedItem();
    }
    
    public void setSelectedItem(T item) {
        jComboBoxItems.setSelectedItem(item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNew = new javax.swing.JButton();
        jComboBoxItems = new javax.swing.JComboBox();

        jButtonNew.setText("New");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNew))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jButtonNew)
                .addComponent(jComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNew;
    private javax.swing.JComboBox jComboBoxItems;
    // End of variables declaration//GEN-END:variables
}
