/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editors;

import java.util.concurrent.Callable;

/**
 *
 * @author nathan
 */
public class guiComboBox<T extends Object> extends javax.swing.JComponent {

    /**
     * Creates new form guiComboBox
     */
    public guiComboBox() {
        initComponents();
    }
    
    public guiComboBox(Iterable<T> items) {
        initComponents();
        this.showNewButton(false);
    }
    
    public guiComboBox(Iterable<T> items, Callable<T> newObject) {
        this(items);
        this.showNewButton(true);
    }
    
    private void showNewButton(boolean show) {
        this.jButtonNew.setVisible(show);
    }
    
    public void setItems(Iterable<T> items) {
        jComboBoxItems.setModel(guiHelper.getComboBoxModel(items));
    }
    
    public int getSelectedIndex() {
        return jComboBoxItems.getSelectedIndex();
    }
    
    public void setSelectedIndex(int index) {
        jComboBoxItems.setSelectedIndex(index);
    }
    
    public T getSelectedItem() {
        return (T)jComboBoxItems.getSelectedItem();
    }
    
    public void setSelectedItem(T item) {
        jComboBoxItems.setSelectedItem(item);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBoxItems = new javax.swing.JComboBox();
        jButtonNew = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        add(jComboBoxItems, java.awt.BorderLayout.CENTER);

        jButtonNew.setText("New");
        add(jButtonNew, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNew;
    private javax.swing.JComboBox jComboBoxItems;
    // End of variables declaration//GEN-END:variables
}
