/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editors;

import java.util.Collection;

/**
 *
 * @author nathan
 */
public class Servo extends ModelEditor<data.Servo> {

    data.Servo servo;
    guiComboBox<data.ServoGroup> groupCombo;
    
    public Servo() {
        super();
        initComponents();
    }

    public Servo(Collection<data.ServoGroup> allServoGroups) {
        this();        
        groupCombo = guiHelper.addComboBox(allServoGroups, this, 1, 1, this.getCallable(data.ServoGroup.class));
    }
    
    private data.ServoGroup newServoGroup() {
        return null;
    }
    
    @Override
    public data.Servo getData() {
        return this.servo;
    }
    
    @Override
    public void setData(data.Servo servo) {
        this.servo = servo;
        this.revertChanges();
    }

    @Override
    public void revertChanges() {     
        this.jTextFieldName.setText(this.servo.getName());
        this.jFormattedTextFieldMaxPosition.setValue(this.servo.getMaxPosition());
        this.jFormattedTextFieldMinPosition.setValue(this.servo.getMinPosition());
        this.jFormattedTextFieldDefaultPosition.setValue(this.servo.getDefaultPosition());
        this.jFormattedTextFieldMaxSpeed.setValue(this.servo.getMaxSpeed());
        this.jFormattedTextFieldMinSpeed.setValue(this.servo.getMinSpeed());
        this.jFormattedTextFieldDefaultSpeed.setValue(this.servo.getDefaultSpeed());
        this.groupCombo.setSelectedItem(this.servo.getServoGroup());
    }
    
    @Override
    public void commitChanges() {
        this.servo.setName(this.jTextFieldName.getText());
        this.servo.setMaxPosition(((Number) this.jFormattedTextFieldMaxPosition.getValue()).intValue());
        this.servo.setMinPosition(((Number) this.jFormattedTextFieldMinPosition.getValue()).intValue());
        this.servo.setDefaultPosition(((Number) this.jFormattedTextFieldDefaultPosition.getValue()).intValue());
        this.servo.setMaxSpeed(((Number) this.jFormattedTextFieldMaxSpeed.getValue()).intValue());
        this.servo.setMinSpeed(((Number) this.jFormattedTextFieldMinSpeed.getValue()).intValue());
        this.servo.setDefaultSpeed(((Number) this.jFormattedTextFieldDefaultSpeed.getValue()).intValue());
        this.servo.setServoGroup(this.groupCombo.getSelectedItem());
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelName = new javax.swing.JLabel();
        jLabelNameMaxPosition = new javax.swing.JLabel();
        jLabelNameMinPosition = new javax.swing.JLabel();
        jLabelNameMaxSpeed = new javax.swing.JLabel();
        jLabelNameMinSpeed = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jFormattedTextFieldMinPosition = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMaxSpeed = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMinSpeed = new javax.swing.JFormattedTextField();
        jLabelNameDefaultPosition = new javax.swing.JLabel();
        jLabelNameDefaultSpeed = new javax.swing.JLabel();
        jFormattedTextFieldDefaultPosition = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDefaultSpeed = new javax.swing.JFormattedTextField();
        jLabelNameServoGroup = new javax.swing.JLabel();
        jFormattedTextFieldMaxPosition = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabelName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelName, gridBagConstraints);

        jLabelNameMaxPosition.setText("Max Position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameMaxPosition, gridBagConstraints);

        jLabelNameMinPosition.setText("Min Position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameMinPosition, gridBagConstraints);

        jLabelNameMaxSpeed.setText("Max Speed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameMaxSpeed, gridBagConstraints);

        jLabelNameMinSpeed.setText("Min Speed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameMinSpeed, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jTextFieldName, gridBagConstraints);

        jFormattedTextFieldMinPosition.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jFormattedTextFieldMinPosition, gridBagConstraints);

        jFormattedTextFieldMaxSpeed.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jFormattedTextFieldMaxSpeed, gridBagConstraints);

        jFormattedTextFieldMinSpeed.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jFormattedTextFieldMinSpeed, gridBagConstraints);

        jLabelNameDefaultPosition.setText("Default Position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameDefaultPosition, gridBagConstraints);

        jLabelNameDefaultSpeed.setText("Default Speed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameDefaultSpeed, gridBagConstraints);

        jFormattedTextFieldDefaultPosition.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jFormattedTextFieldDefaultPosition, gridBagConstraints);

        jFormattedTextFieldDefaultSpeed.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jFormattedTextFieldDefaultSpeed, gridBagConstraints);

        jLabelNameServoGroup.setText("Servo Group");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameServoGroup, gridBagConstraints);

        jFormattedTextFieldMaxPosition.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jFormattedTextFieldMaxPosition, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonCancel, gridBagConstraints);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonOK, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.close(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.close(true);
    }//GEN-LAST:event_jButtonOKActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JFormattedTextField jFormattedTextFieldDefaultPosition;
    private javax.swing.JFormattedTextField jFormattedTextFieldDefaultSpeed;
    private javax.swing.JFormattedTextField jFormattedTextFieldMaxPosition;
    private javax.swing.JFormattedTextField jFormattedTextFieldMaxSpeed;
    private javax.swing.JFormattedTextField jFormattedTextFieldMinPosition;
    private javax.swing.JFormattedTextField jFormattedTextFieldMinSpeed;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameDefaultPosition;
    private javax.swing.JLabel jLabelNameDefaultSpeed;
    private javax.swing.JLabel jLabelNameMaxPosition;
    private javax.swing.JLabel jLabelNameMaxSpeed;
    private javax.swing.JLabel jLabelNameMinPosition;
    private javax.swing.JLabel jLabelNameMinSpeed;
    private javax.swing.JLabel jLabelNameServoGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
