/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editors;

import java.util.Collection;

/**
 *
 * @author nathan
 */
public class ServoPosition extends ModelEditor<data.ServoPosition> {

    guiComboBox<data.Pose> poseCombo;
    
    public ServoPosition() {
        super();
        initComponents();
    }

    public ServoPosition(Collection<data.Pose> allPoses) {
        this();        
        poseCombo = guiHelper.addComboBox(allPoses, this, 1, 1, null);
    }
    
    private data.ServoGroup newServoGroup() {
        return null;
    }

    @Override
    public void revertChanges() {     
        this.jTextFieldName.setText(this.model.getServoName());
        this.jCheckBoxWaitForComplete.setSelected(this.model.getWaitForComplete());
        this.jSliderPosition.setValue(this.model.getPosition());
        this.jSliderSpeed.setValue(this.model.getSpeed());
        this.poseCombo.setSelectedItem(this.model.getPose());
    }
    
    @Override
    public void commitChanges() {
        this.model.setServoName(this.jTextFieldName.getText());
        this.model.setWaitForComplete(this.jCheckBoxWaitForComplete.isSelected());
        this.model.setPosition(this.jSliderPosition.getValue());
        this.model.setSpeed(this.jSliderSpeed.getValue());
        this.model.setPose(this.poseCombo.getSelectedItem());
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelName = new javax.swing.JLabel();
        jLabelNamePosition = new javax.swing.JLabel();
        jLabelNameSpeed = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jSliderSpeed = new javax.swing.JSlider();
        jLabelNamePose = new javax.swing.JLabel();
        jSliderPosition = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jCheckBoxWaitForComplete = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        jLabelName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelName, gridBagConstraints);

        jLabelNamePosition.setText("Position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNamePosition, gridBagConstraints);

        jLabelNameSpeed.setText("Speed");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNameSpeed, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jTextFieldName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jSliderSpeed, gridBagConstraints);

        jLabelNamePose.setText("Pose");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabelNamePose, gridBagConstraints);

        jSliderPosition.setMajorTickSpacing(45);
        jSliderPosition.setMaximum(360);
        jSliderPosition.setMinorTickSpacing(15);
        jSliderPosition.setValue(180);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jSliderPosition, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonCancel, gridBagConstraints);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonOK, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jPanel1, gridBagConstraints);

        jCheckBoxWaitForComplete.setText("Wait for Complete");
        jCheckBoxWaitForComplete.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jCheckBoxWaitForComplete, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.close(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.close(true);
    }//GEN-LAST:event_jButtonOKActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxWaitForComplete;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNamePose;
    private javax.swing.JLabel jLabelNamePosition;
    private javax.swing.JLabel jLabelNameSpeed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderPosition;
    private javax.swing.JSlider jSliderSpeed;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
