module.exports = {
	libs : {
		options : {
			srcPrefix : './bower_components',
			destPrefix : './build/bower_components'
		},
		files : {
			"angular/angular.js" : "angular/angular.js",
			"angular/angular.min.js" : "angular/angular.min.js",
			"angular/angular.min.js.map" : "angular/angular.min.js.map",
			"angular-bootstrap/ui-bootstrap-tpls.js" : "angular-bootstrap/ui-bootstrap-tpls.js",
			"angular-bootstrap/ui-bootstrap-tpls.min.js" : "angular-bootstrap/ui-bootstrap-tpls.min.js",
			"angular-resource/angular-resource.js" : "angular-resource/angular-resource.js",
			"angular-resource/angular-resource.min.js" : "angular-resource/angular-resource.min.js",
			"angular-resource/angular-resource.min.js.map" : "angular-resource/angular-resource.min.js.map",
			"angular-ui-router/release/angular-ui-router.js" : "angular-ui-router/release/angular-ui-router.js",
			"angular-ui-router/release/angular-ui-router.min.js" : "angular-ui-router/release/angular-ui-router.min.js",
			"angular-ui-slider/src/slider.js" : "angular-ui-slider/src/slider.js",
			"angular-xeditable/dist/js/xeditable.js" : "angular-xeditable/dist/js/xeditable.js",
			"angular-xeditable/dist/js/xeditable.min.js" : "angular-xeditable/dist/js/xeditable.min.js",
			"angular-xeditable/dist/css/xeditable.css" : "angular-xeditable/dist/css/xeditable.css",
			"bootstrap/dist/css" : "bootstrap/dist/css",
			"bootstrap/dist/fonts" : "bootstrap/dist/fonts",
			"jquery/jquery.js" : "jquery/jquery.js",
			"jquery/jquery.min.js" : "jquery/jquery.min.js",
			"jquery/jquery.min.map" : "jquery/jquery.min.map",
			"jquery-ui/themes/smoothness" : "jquery-ui/themes/smoothness",
			"jquery-ui/ui/jquery-ui.js" : "jquery-ui/ui/jquery-ui.js",
			"jquery-ui/ui/minified/jquery-ui.min.js" : "jquery-ui/ui/minified/jquery-ui.min.js",
			"jquery-ui/ui/i18n/jquery-ui-i18n.js" : "jquery-ui/ui/i18n/jquery-ui-i18n.js",
			"jquery-ui/ui/minified/i18n/jquery-ui-i18n.min.js" : "jquery-ui/ui/minified/i18n/jquery-ui-i18n.min.js",
			"mousetrap/mousetrap.js" : "mousetrap/mousetrap.js",
			"mousetrap/mousetrap.min.js" : "mousetrap/mousetrap.min.js",
			"mousetrap/plugins/pause/mousetrap-pause.js" : "mousetrap/plugins/pause/mousetrap-pause.js",
			"mousetrap/plugins/pause/mousetrap-pause.min.js" : "mousetrap/plugins/pause/mousetrap-pause.min.js",
			"requirejs/require.js" : "requirejs/require.js",
			"requirejs-text/text.js" : "requirejs-text/text.js",
			"socket.io-client/dist/socket.io.js" : "socket.io-client/dist/socket.io.js",
			"socket.io-client/dist/socket.io.min.js" : "socket.io-client/dist/socket.io.min.js",
			"socket.io-client/dist/WebSocketMain.swf" : "socket.io-client/dist/WebSocketMain.swf",
			"underscore/underscore.js" : "underscore/underscore.js",
			"underscore/underscore-min.js" : "underscore/underscore-min.js",
			"underscore/underscore-min.map" : "underscore/underscore-min.map",
		}
	},
}
